include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - '**.g.dart'
    - '**.freezed.dart'

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    require_trailing_commas: false
    use_super_parameters: false
    sort_pub_dependencies: false
    avoid_bool_literals_in_conditional_expressions: false
    avoid_relative_lib_imports: false
    always_use_package_imports: false
    avoid_multiple_declarations_per_line: false

formatter:
  page_width: 80
  trailing_commas: preserve