include: package:lint/strict.yaml

analyzer:
  errors:
    # [unused_element reports on unused parameters whose presence is idiomatic · Issue #49025 · dart-lang/sdk](https://github.com/dart-lang/sdk/issues/49025)
    unused_element: ignore

# Instead of disabling a lint rule it can also be suppressed:
# `// ignore: name_of_lint` - a single line of code
# `// ignore_for_file: name_of_lint` - syntax on the line or in the file
linter:
  rules:
    require_trailing_commas: false
    avoid_relative_lib_imports: false
    always_use_package_imports: false
    use_super_parameters: true
    sort_pub_dependencies: false
