name: weather_scenes
description: "Application for viewing built-in weather scenes"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  weather_animation:
#    path: ../../../weather_animation # for development
    git:
      url: https://github.com/PackRuble/weather_animation

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
