
name: Build & Deploy weathunits_configurator

on:
  # we do this on purpose, since not every version needs a new build
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#  push:
#    branches: [master]
#    paths:
#      - 'example/weathunits_configurator'
#      - '!**.md' # ignore the readme files

jobs:

  build-and-deploy:
    name: 'Build & Deploy web app'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Install Flutter and Dart SDK'
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: 'Show Flutter SDK version'
        run: flutter --version

      - name: 'Flutter enable Web'
        run: flutter config --enable-web

      - name: 'Flutter clean before build'
        run: |
          flutter clean
          cd 'example/weathunits_configurator'
          flutter clean

      - name: 'Get dependencies'
        run: flutter pub get
        working-directory: example/weathunits_configurator

      - name: 'Show outdated packages'
        run: flutter pub outdated

      - name: 'Build web app'
        run: |
          cd example/weathunits_configurator
          flutter build web --base-href='/weather_animation/' --web-renderer=skwasm

      - name: 'Deploy web app'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: 'example/weathunits_configurator/build/web'
          single-commit: true
